version: "3.1"
services:
  pylucene:
    container_name: pylucene
    build: ./pylucene/
    image: pylucene
    ports:
      - "8043:8043"
    networks:
      - documents_traefik
    volumes:
      - ./data:/index/
    environment:
      - SE_ALLOW_UNSAFE_SSL=TRUE
    labels:
      - "traefik.http.routers.pylucene.rule=PathPrefix(`/pylucene`)"
      - "traefik.http.routers.pylucene.middlewares=pylucene"
      - "traefik.http.middlewares.pylucene.stripprefix.prefixes=/pylucene"
      - "traefik.http.routers.pylucene.entrypoints=web"
      - "traefik.enable=true"

  availability-proxy:
    container_name: availability-proxy
    build: ./status_proxy
    image: availability-proxy
    networks:
      - documents_traefik
    ports:
      - "8042:8042"
    environment:
      - SE_BACKEND_SERVER=http://pylucene:8043
      - SE_ALLOW_UNSAFE_SSL=TRUE
    labels:
      - "traefik.http.routers.availability-proxy.rule=PathPrefix(`/search-engine`)"
      - "traefik.http.routers.availability-proxy.middlewares=availability-proxy"
      - "traefik.http.middlewares.availability-proxy.stripprefix.prefixes=/search-engine"
      - "traefik.http.routers.availability-proxy.entrypoints=web"
      - "traefik.enable=true"

networks:
  documents_traefik:
    external: true
